app/controllers/movimentacao/forms.py
from flask_wtf import Form
from wtforms import StringField, BooleanField, FloatField, IntegerField, DateField,TextAreaField, SelectField, FileField,validators
from wtforms.validators import DataRequired
from app.model import Categoria,Formapagamento
from datetime import datetime

class MovForm(Form):


     freq  = [
               (1,'Uma única vez'),
               (1000,'Diariamente'),
               (1200,'Semanal'),
               (1300,'A cada 10 dias'),
               (1400,'A cada 15 dias'),
               (1500,'A cada 28 dias'),
               (1600,'Mensal'),
               (1700,'Bimestral'),
               (1800,'Trimestral'),
               (1900,'Quadrimestral'),
               (2000,'Semestral'),
               (2100, 'Anual') 
             ] 


#     nparcelas = []
#     nparcelas.append((0,'Conta Fixa'))
#     nparcelas.append((1000,'Finalizar - Conta Fixa'))
     for a in range(2,500):
        freq.append((a,'%d-Parcelas' %a))

     #Contas Canceladas
     freq.append((5000,'Cancelamento'))   


     titulo       = StringField('titulo', validators=[DataRequired()])
     descricao    = TextAreaField('titulo', validators=[DataRequired()])
     valor        = FloatField('valor', validators=[DataRequired()])
     parcelas     = SelectField('parcelas', choices=freq,coerce=int)
     data_v       = DateField("Until", format="%d/%m/%Y",default=datetime.today, validators=[validators.DataRequired()])
     categoria_id = SelectField('categorias',coerce=int)
     conta_id     = SelectField('Conta',coerce=int)

     formapagamento_id = SelectField('formapagamento', coerce=int)



class MovRealizadoForm(Form):
     valor           = FloatField('valor', validators=[DataRequired()])
     juros           = FloatField('juros', default=0.0)
     multa           = FloatField('multa', default=0.0)
     desconto        = FloatField('desconto', default=0.0)
     data_pagamento  = DateField("Pagamento", format="%d/%m/%Y",default=datetime.today, validators=[validators.DataRequired()])
     comprovante     =  FileField('comprovante')

class DocsForm(Form):
     boleto       =  FileField('boleto')
     comprovante  =  FileField('comprovante')
     outros       =  FileField('outros')


class RelForm(Form):
     efetuado    =  BooleanField('efetuado')
#posted_date = DateField('Posted Date (mm/dd/yyyy)',validators=[required()],format='%m/%d/%Y')


class PesqForm(Form):
      campo      = StringField('campo', validators = [DataRequired()])
       

app/controllers/movimentacao/controllers.py
import datetime
from app import db
from sqlalchemy.sql import func
from config import UPLOAD_FOLDER
from werkzeug import secure_filename
from app.crontab import cad_parcelado
from flask_login import login_required, current_user
from flask_babel import format_currency, format_decimal
from configExtrato import ALLOWED_EXTENSIONS, UPLOAD_EXTRATO
from flask import send_from_directory, Flask, request, jsonify
from app.model import Movimentacao,Docs, Categoria, Formapagamento, Usuario, Empresa, Conta, Planejamento, Alert
from flask import render_template, flash, redirect, request,session, redirect, Blueprint, url_for
from app.controllers.movimentacao.forms import MovForm, MovRealizadoForm, DocsForm, RelForm, PesqForm
import json

movimentacao = Blueprint('movimentacao',__name__)

@movimentacao.route('/index/<int:mov_id>')
@movimentacao.route('/<int:mov_id>')
@login_required
def index(mov_id):
    if mov_id == 0:
        session['tela'] = 'entrada'
    elif mov_id == 1:
        session['tela'] = 'saida'

    todos = Movimentacao.query.join(Categoria, Movimentacao.categoria_id == Categoria.id).filter(Categoria.status == mov_id,Movimentacao.efetuado == None, Movimentacao.empresa_id == session['empresa'] ).order_by('data_v').all()
    soma = sum([item.valor for item in todos])

    set_alerts(session['empresa'])
    return render_template('movimentacao/index.html', title = 'Lista de Contas', todos = todos, sum = soma)

@movimentacao.route('/new', methods = ['GET','POST'])
@login_required
def new():
    form = MovForm()
    form.categoria_id.choices = [(h.id,str(h.id) + ' ' + h.titulo) for h in Categoria.query.filter(Categoria.empresa_id == session['empresa']).all() ]
    form.formapagamento_id.choices = [(h.id,h.tipo) for h in Formapagamento.query.all()]
    form.conta_id.choices = [(h.id,h.tipo + '-' + h.conta) for h in Conta.query.filter(Conta.empresa_id == session['empresa']).all() ]

    if form.validate_on_submit():
        mov = Movimentacao(
            titulo            = form.titulo.data,
            descricao         = form.descricao.data,
            valor             = form.valor.data,
            parcelas          = form.parcelas.data,
            data_v            = form.data_v.data,
            categoria_id      = form.categoria_id.data,
            formapagamento_id = form.formapagamento_id.data,
            conta_id          = form.conta_id.data
        )
        mov.empresa_id = session['empresa']
        mov.add(mov)
        mov.parcelas_id = mov.get_id()
        mov.update()
        
        cad_parcelado.delay(mov.id)

        if session['tela'] == 'entrada':
            mov_id = 0
        else:
            mov_id = 1
        
        return redirect(url_for('movimentacao.index', mov_id = mov_id))
    return render_template('movimentacao/new.html', title = 'Cadastro de Novas Contas', form = form)

@movimentacao.route('/edit/<int:mov_id>', methods = ['GET','POST'])
@login_required
def edit(mov_id):
    mov = Movimentacao.query.get(mov_id)
    form = MovForm(obj=mov)
    form.categoria_id.choices = [(h.id,h.titulo) for h in Categoria.query.all()]
    form.formapagamento_id.choices = [(h.id,h.tipo) for h in Formapagamento.query.all()]
    form.conta_id.choices = [(h.id,h.tipo + '-' + h.conta) for h in Conta.query.all()]

    cat_old_id = mov.categoria_id
    print('cat_old_id: ' + str(cat_old_id))
    cat_new_id = form.categoria_id.data
    print('cat_new_id: ' + str(cat_new_id))
    
    if form.validate_on_submit():
        mov.titulo       = form.titulo.data
        mov.descricao    = form.descricao.data
        mov.valor        = form.valor.data
        mov.parcelas     = form.parcelas.data
        mov.data_v       = form.data_v.data
        mov.categoria_id = form.categoria_id.data                          
        mov.formapagamento_id = form.formapagamento_id.data
        mov.conta_id     = form.conta_id.data
        mov.update()

        if session['tela'] == 'entrada':
            mov_id = 0
        else:
            mov_id = 1

        # atualiza as palavras-chaves das categorias
        cat_old = Categoria.query.get(cat_old_id)
        cat_old.keywords = ''
        movs_cat_old = Movimentacao.query.filter(Movimentacao.categoria_id == cat_old_id).all()
        print('movs_cat_old: ' + str(movs_cat_old))
        if len(movs_cat_old) > 0:
            for m in movs_cat_old:
                if len(movs_cat_old) == 1:
                    cat_old.keywords = m.titulo
                    print('1 - cat_old_keywords: ' + cat_old.keywords)
                else:
                    if movs_cat_old.index(m) < (len(movs_cat_old) - 1):
                        cat_old.keywords = cat_old.keywords + m.titulo + ' ; '
                        print('2 - cat_old_keywords: ' + cat_old.keywords)
                    else:
                        cat_old.keywords = cat_old.keywords + m.titulo
                        print('3 - cat_old_keywords: ' + cat_old.keywords)
            print('final - cat_old_keywords: ' + cat_old.keywords)
        cat_old.update()

        cat_new = Categoria.query.get(mov.categoria_id)
        cat_new.keywords = ''
        movs_cat_new = Movimentacao.query.filter(Movimentacao.categoria_id == mov.categoria_id).all()
        print('movs_cat_new: ' + str(movs_cat_new))
        if len(movs_cat_new) > 0:
            for m in movs_cat_new:
                if len(movs_cat_new) == 1:
                    cat_new.keywords = m.titulo
                    print('1 - cat_new_keywords: ' + cat_new.keywords)
                else:
                    if movs_cat_new.index(m) < (len(movs_cat_new) - 1):
                        cat_new.keywords = cat_new.keywords + m.titulo + ' ; '
                        print('2 - cat_new_keywords: ' + cat_new.keywords)
                    else:
                        cat_new.keywords = cat_new.keywords + m.titulo
                        print('3 - cat_new_keywords: ' + cat_new.keywords)
            print('final - cat_new_keywords: ' + cat_new.keywords)
        cat_new.update()

        return redirect(url_for('movimentacao.index', mov_id = mov_id))
    return render_template('movimentacao/edit.html', title = 'Alterar de Lançamento', form = form)

@movimentacao.route('/realizado/<int:mov_id>', methods = ['GET','POST'])
@login_required
def realizado(mov_id):
    mov = Movimentacao.query.get(mov_id)
    form = MovRealizadoForm(valor = mov.valor)

    if form.validate_on_submit():
        mov.valor          = form.valor.data
        mov.juros          = form.juros.data
        mov.desconto       = form.desconto.data
        mov.multa          = form.multa.data
        mov.data_pagamento = form.data_pagamento.data
        mov.efetuado       = True
        
        filename_c         = secure_filename(form.comprovante.data.filename)
        if filename_c:
            upload_docs(filename_c,mov,form,1)
        
        mov.update()

        if session['tela'] == 'entrada':
            mov_id = 0
        else:
            mov_id = 1
        
        return redirect(url_for('movimentacao.index', mov_id = mov_id))
    return render_template('movimentacao/realizado.html', title = 'Lançamento', form = form, mov = mov)    

@movimentacao.route('/delete/<int:mov_id>')
@login_required
def delete(mov_id):
    mov = Movimentacao.query.get(mov_id)
 
    # Verificar se existe movimentação do usuário antes de apagar ou apagar todas as movimentacoes
    mov.delete(mov)

    if session['tela'] == 'entrada':
        mov_id = 0
    else:
        mov_id = 1            

    return redirect(url_for('movimentacao.index', mov_id = mov_id))

@movimentacao.route('/docs/<int:mov_id>', methods = ('GET', 'POST'))
@login_required
def docs(mov_id):
    mov = Movimentacao.query.get(mov_id)
    form = DocsForm()
    if form.validate_on_submit():
        filename_b = secure_filename(form.boleto.data.filename)
        if filename_b:
            upload_docs(filename_b,mov,form,0)
            
        filename_c = secure_filename(form.comprovante.data.filename)
        if filename_c:
            upload_docs(filename_c,mov,form,1)
            
        filename_o = secure_filename(form.outros.data.filename)
        if filename_o:
            upload_docs(filename_o,mov,form,2)
        
        db.session.commit()
        
        if session['tela'] == 'entrada':
            mov_id = 0
        else:
            mov_id = 1
            
        return redirect(url_for('movimentacao.index', mov_id = mov_id))
    return render_template('movimentacao/docs.html', title = 'Anexo de Movimentação', form = form, mov = mov)

@movimentacao.route('/docs_delete/<int:file_id>', methods = ('GET', 'POST'))
@login_required
def docs_delete(file_id):
    file = Docs.query.get(file_id)
    file.delete(file)
    
    if session['tela'] == 'entrada':
        mov_id = 0
    else:
        mov_id = 1
        
    return redirect(url_for('movimentacao.index', mov_id = mov_id))

@movimentacao.route('/pesquisa', methods = ('GET', 'POST'))
@login_required
def pesquisa():
    session['tela'] = 'pesquisa'    
    form = PesqForm()
    if form.validate_on_submit():
        campo = form.campo.data
        todos = Movimentacao.query.filter((Movimentacao.titulo.like('%'+campo+'%')) | (Movimentacao.descricao.like('%'+campo+'%')), Movimentacao.empresa_id == session['empresa'] ).order_by('data_v DESC').all()
    else:
        todos = Movimentacao.query.filter(Movimentacao.efetuado,Movimentacao.empresa_id == session['empresa'] ).order_by('data_v DESC').all()
        
    return render_template('movimentacao/pesquisa.html', title = 'Pesquisa de Contas', todos = todos, form = form)

@login_required
def upload_docs(filename,mov,form,tipo):
    # Tipo
    #  0 - Boleto
    #  1 - Comprovante
    #  2 - Outros
    user = current_user.id
    filename = str(mov.id) + '_' + str(user)+'_'+filename
    path = UPLOAD_FOLDER+'/'+filename
    if tipo == 0:
        file_tipo = 'BOLETO'
        form.boleto.data.save(path)
    elif tipo == 1:

app/templates/movimentacao/docs.html
<!-- extend from base layout -->

{% extends "layout/base.html" %}


{% block content %}

    
   <div class="space-12"></div>

										<div class="profile-user-info profile-user-info-striped">
											<div class="profile-info-row">
												<div class="profile-info-name"> Título </div>

												<div class="profile-info-value">
													<span>{{mov.titulo}}</span>
												</div>
											</div>

											<div class="profile-info-row">
												<div class="profile-info-name"> Descrição </div>

												<div class="profile-info-value">
													<span>{{mov.descricao}}</span>
												</div>
											</div>

											<div class="profile-info-row">
												<div class="profile-info-name"> Data de Vencimento </div>

												<div class="profile-info-value">
													<span>{{mov.data_v}}</span>
												</div>
											</div>

											<div class="profile-info-row">
												<div class="profile-info-name"> Categoria </div>

												<div class="profile-info-value">
													<span >{{mov.categoria.titulo}}</span>
												</div>
											</div>

                     {% for file in mov.docs %} 
  							<div class="profile-info-row"> 
								<div class="profile-info-name"> {{file.tipo.title()}} </div>
									<div class="profile-info-value">

                           	<span>
                                  <a  data-target="#{{file.id}}" data-toggle="modal" >{{file.filename}} </a> &nbsp; 
                                  <a href="{{url_for('movimentacao.docs_delete', file_id=file.id)}}"><span class="icon-fixed-width icon-trash" aria-hidden="true"/></a>
                           </span>
												</div>
                            </div>  
                    
                    <div id={{file.id}} class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
                         <div class="modal-dialog modal-lg">
                              <div class="modal-header">
                                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                  <h4 class="modal-title" id="myModalLabel"><strong> {{file.tipo.title()}}:&nbsp; &nbsp;</strong>{{file.filename}}  </h4>
                              </div>
                         <div class="modal-body">
                                 <div class="modal-content">
                                   <object type="application/pdf" data="{{ url_for('static', filename=file.path.split('static')[1][1:])}}" width="900" height="900"> Documento n encontrado</object>
                                 </div>
                             </div>
                        </div>
                    </div>                                   
                  {% endfor %}

											
	</div>


    

    
    
    


    <form action="" method="post" name="docs" enctype="multipart/form-data" class="form-horizontal">
          {{form.hidden_tag() }}
      <p>
           {% for error in form.errors %}
                   <span style="color: red;">[{{ error }}] </span>
                {%  endfor%} <br>
       </p>

        <div class="control-group">
					   <label class="control-label" for="form-field-1">Boleto</label>
					  <div class="controls">
                     {{ form.boleto }}
					  </div>
			</div>
        <div class="control-group">
					   <label class="control-label" for="form-field-1">Comprovante</label>
					  <div class="controls">
                     {{ form.comprovante }}
					  </div>
			</div>
        <div class="control-group">
					   <label class="control-label" for="form-field-1">Outros</label>
					  <div class="controls">
                     {{ form.outros }}
					  </div>
			</div>

               <div class="form-actions">
	  				<input type="submit" value="Salvar" class="btn btn-info">   
              </div>

      </form>

<div class="space-12"></div>

					<div class="profile-user-info profile-user-info-striped">
											
                     {% for file in mov.docs %} 
  							<div class="profile-info-row"> 
								<div class="profile-info-name"> {{file.tipo.title()}} ({{ file.data_v }}) </div>
									<div class="profile-info-value">

                           	<span>
                                  <a  data-target="#{{file.id}}" data-toggle="modal" >{{file.filename}} </a> &nbsp; 
                                  <a href="{{url_for('movimentacao.docs_delete', file_id=file.id)}}"><span class="icon-fixed-width icon-trash" aria-hidden="true"/></a>
                           </span>
												</div>
                            </div>  
                    
                    <div id={{file.id}} class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
                         <div class="modal-dialog modal-lg">
                              <div class="modal-header">
                                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                  <h4 class="modal-title" id="myModalLabel"><strong> {{file.tipo.title()}}:&nbsp; &nbsp;</strong>{{file.filename}}  </h4>
                              </div>
                         <div class="modal-body">
                                 <div class="modal-content">
                                   <object type="application/pdf" data="{{ url_for('static', filename=file.path.split('static')[1][1:])}}" width="900" height="900"> Documento n encontrado</object>
                                 </div>
                             </div>
                        </div>
                    </div>                                   
                  {% endfor %}

											
	</div>

      
{% endblock %}

app/templates/movimentacao/index.html
{% extends "layout/base.html" %}

{% block content %}




					<div class="row-fluid">
						<div class="span12">
							<!--PAGE CONTENT BEGINS-->

							<div class="row-fluid">
								<div class="span12">
									<table id="sample-table-1" class="table table-striped table-bordered table-hover">
										<thead>
											<tr>			
												<th class="hidden-480"> Dt. Vencimento</th>									
												<th>Lançamento </th>
												<th>Descrição</th>
												<th>Categoria</th>
												<th>Parcelas</th>
												<th>Valor</th>												
												<th></th>
											</tr>
										</thead>

										<tbody>
                                   {% for conta in todos %}
                                            {% if hoje >  conta.data_v %}    
                                                <tr class="danger">                                                	
                                            {% elif hoje == conta.data_v %}
                                                <tr class="warning">
                                            {% else %}
                                                  <tr>      
                                           
                                            {% endif %}   
											
                                      <td >{{ conta.data_v.strftime('%d/%m/%Y') }}</td>
                                    <td class="hidden-480">{{ conta.titulo }}</td>
												<td>{{ conta.descricao[:30] }}</td>
												<td>{{ conta.categoria.titulo }}</td>
  				  					            <td>{{ parcelas(conta.parcelas,conta.parcelas_id)}}</td>
												<td>{{ formatar_dinheiro(conta.valor)}}</td>	
												
												    
												
												

												<td>
													<div class="hidden-phone visible-desktop btn-group">
														<a class="btn btn-mini btn-success" href="{{url_for('movimentacao.realizado', mov_id=conta.id)}}"> 
                                                         <i class="icon-ok bigger-120">   </i>                                       
                                                     </a>
                                                     <a class="btn btn-mini btn-action" href="{{url_for('movimentacao.docs', mov_id=conta.id)}}"> 
                                                         <i class="icon-hdd  bigger-120">   </i>
                                                        
                                       
                                                     </a>										

                                                       <a class="btn btn-mini btn-info" href="{{url_for('movimentacao.edit', mov_id=conta.id)}}"> 
															<i class="icon-edit bigger-120">   </i>                                             
														</a>

														<a class="btn btn-mini btn-danger" href="{{url_for('movimentacao.delete', mov_id=conta.id)}}">
															<i class="icon-trash bigger-120"></i>
														</a>

														
													</div>

													
												</td>
											</tr>
										{% endfor %}				

										</tbody>
									</table>
								</div><!--/span-->
							</div><!--/row-->
                  

    <div class="hr hr8 hr-double hr-dotted"></div>
         <div class="row-fluid">
            <div class="span5 pull-right">
                <h4 class="pull-right">
                    Total:
                    <span class="red">{{ formatar_dinheiro(sum)   }} </span>
                </h4>
            </div>                            
        </div>
  </div>

							
							<div class="hr hr-18 dotted hr-double"></div>
                           <div class="left">
											<a href="{{url_for('movimentacao.new')}}" class="btn btn-primary">
												<i class="icon-plus"></i>
												<strong>LANÇAMENTOS</strong>
											</a>
										</div>






 							

							
						</div><!--/.span-->
					</div><!--/.row-fluid-->
				</div><!--/.page-content-->

				<div class="ace-settings-container" id="ace-settings-container">
					<div class="btn btn-app btn-mini btn-warning ace-settings-btn" id="ace-settings-btn">
						<i class="icon-cog bigger-150"></i>
					</div>

					<div class="ace-settings-box" id="ace-settings-box">
						<div>
							<div class="pull-left">
								<select id="skin-colorpicker" class="hide">
									<option data-class="default" value="#438EB9" />#438EB9
									<option data-class="skin-1" value="#222A2D" />#222A2D
									<option data-class="skin-2" value="#C6487E" />#C6487E
									<option data-class="skin-3" value="#D0D0D0" />#D0D0D0
								</select>
							</div>
							<span>&nbsp; Choose Skin</span>
						</div>

						<div>
							<input type="checkbox" class="ace-checkbox-2" id="ace-settings-header" />
							<label class="lbl" for="ace-settings-header"> Fixed Header</label>
						</div>

						<div>
							<input type="checkbox" class="ace-checkbox-2" id="ace-settings-sidebar" />
							<label class="lbl" for="ace-settings-sidebar"> Fixed Sidebar</label>
						</div>

						<div>
							<input type="checkbox" class="ace-checkbox-2" id="ace-settings-breadcrumbs" />
							<label class="lbl" for="ace-settings-breadcrumbs"> Fixed Breadcrumbs</label>
						</div>

						<div>
							<input type="checkbox" class="ace-checkbox-2" id="ace-settings-rtl" />
							<label class="lbl" for="ace-settings-rtl"> Right To Left (rtl)</label>
						</div>
					</div>
				</div><!--/#ace-settings-container-->
			</div><!--/.main-content-->
		</div><!--/.main-container-->

		<a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-small btn-inverse">
			<i class="icon-double-angle-up icon-only bigger-110"></i>
		</a>


{% endblock %}

app/templates/movimentacao/pesquisa.html
{% extends "layout/base.html" %}

{% block content %}

                      <div class="space-6"></div>

									<div class="row-fluid">
										<div class="widget-box">
											<div class="widget-header widget-header-small">
												<h5 class="lighter">Pesquisa</h5>
											</div>

											<div class="widget-body">
												<div class="widget-main">
													<form class="form-search" action="pesquisa" method="post" name="new">
														{{form.hidden_tag() }}
														{{ form.campo(class_="input-medium search-query") }} 
															
														<button type="submit" class="btn btn-purple btn-small">
															Pesquisa
															<i class="icon-search icon-on-right bigger-110"></i>
														</button>
													</form>
												</div>
											</div>
										</div>
									</div>
              								
                      <div class="space-6"></div>


					<div class="row-fluid">
						<div class="span12">
							<!--PAGE CONTENT BEGINS-->

							<div class="row-fluid">
								<div class="span12">
									<table id="sample-table-1" class="table table-striped table-bordered table-hover">
										<thead>
											<tr>											   
												<th class="hidden-480"> Dt. Vencimento</th>									
												<th>Lançamento </th>
												<th>Descrição</th>
												<th>Categoria</th>
												<th>Parcelas</th>
												<th>Valor</th>
												<th>Anexos</th>
												<th></th>												
											</tr>
										</thead>

										<tbody>
                                   {% for conta in todos %}

											<tr>
												
                                      <td >{{ conta.data_v.strftime('%d/%m/%Y') }}</td>
                                    <td class="hidden-480">{{ conta.titulo }}</td>
												<td>{{ conta.descricao[:30] }}</td>
												<td>{{ conta.categoria.titulo }}</td>
                                   {% if conta.parcelas != 0  and conta.parcelas != 1000 %}
                                     {% set n = [0] %}
                                     {% for mov in todos %}
                                       {% if mov.parcelas_id == conta.parcelas_id %}
                                          {% if n.append(n.pop() + 1) %}{% endif %}  
                                       {% endif %}
                                     {% endfor %}
				  					      <td>{{ n.pop() }} de {{conta.parcelas}}</td>
                                   {% else %}
                  	  					<td>FIXA</td>
                                   {% endif %}
												{% if conta.categoria.status == 0 %}
												   <td>R$ {{(conta.valor + conta.juros + conta.multa) - conta.desconto}}</td>	
												{% else %}
												    <td>R$ ( {{(conta.valor + conta.juros + conta.multa) - conta.desconto}} )</td>
												{% endif %}

												<td class="hidden-480"><a href="{{url_for('movimentacao.docs', mov_id=conta.id)}}"> Anexos </a></td>
												<td>
													<div class="hidden-phone visible-desktop btn-group">														

                                          <a class="btn btn-mini btn-info" href="{{url_for('movimentacao.edit', mov_id=conta.id)}}"> 
															<i class="icon-edit bigger-120">   </i>                                             
														</a>

														<a class="btn btn-mini btn-danger" href="{{url_for('movimentacao.delete', mov_id=conta.id)}}">
															<i class="icon-trash bigger-120"></i>
														</a>

														
													</div>

													
												</td>

																							</tr>
										{% endfor %}				

										</tbody>
									</table>
                                <div class="pagination pagination-right">
										<ul>
											<li class="disabled">
												<a href="#">
													<i class="icon-double-angle-left"></i>
												</a>
											</li>

											<li class="active">
												<a href="#">1</a>
											</li>

											<li>
												<a href="#">2</a>
											</li>

											<li>
												<a href="#">3</a>
											</li>

											<li>
												<a href="#">4</a>
											</li>

											<li>
												<a href="#">5</a>
											</li>

											<li>
												<a href="#">
													<i class="icon-double-angle-right"></i>
												</a>
											</li>
										</ul>
									</div>
								</div><!--/span-->
							</div><!--/row-->
						</div><!--/.span-->

					</div><!--/.row-fluid-->

				</div><!--/.page-content-->


				<div class="ace-settings-container" id="ace-settings-container">
					<div class="btn btn-app btn-mini btn-warning ace-settings-btn" id="ace-settings-btn">
						<i class="icon-cog bigger-150"></i>
					</div>

					<div class="ace-settings-box" id="ace-settings-box">
						<div>
							<div class="pull-left">
								<select id="skin-colorpicker" class="hide">
									<option data-class="default" value="#438EB9" />#438EB9
									<option data-class="skin-1" value="#222A2D" />#222A2D
									<option data-class="skin-2" value="#C6487E" />#C6487E
									<option data-class="skin-3" value="#D0D0D0" />#D0D0D0
								</select>
							</div>
							<span>&nbsp; Choose Skin</span>
						</div>

						<div>
							<input type="checkbox" class="ace-checkbox-2" id="ace-settings-header" />
							<label class="lbl" for="ace-settings-header"> Fixed Header</label>
						</div>

						<div>
							<input type="checkbox" class="ace-checkbox-2" id="ace-settings-sidebar" />
							<label class="lbl" for="ace-settings-sidebar"> Fixed Sidebar</label>
						</div>

						<div>
							<input type="checkbox" class="ace-checkbox-2" id="ace-settings-breadcrumbs" />
							<label class="lbl" for="ace-settings-breadcrumbs"> Fixed Breadcrumbs</label>
						</div>

						<div>
							<input type="checkbox" class="ace-checkbox-2" id="ace-settings-rtl" />
							<label class="lbl" for="ace-settings-rtl"> Right To Left (rtl)</label>
						</div>
					</div>
				</div><!--/#ace-settings-container-->
			</div><!--/.main-content-->
		</div><!--/.main-container-->

		<a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-small btn-inverse">
			<i class="icon-double-angle-up icon-only bigger-110"></i>
		</a>


{% endblock %}