app/controllers/empresa/forms.py
from flask_wtf import Form
from wtforms import StringField, BooleanField, FloatField, IntegerField, DateField,TextAreaField, SelectField, FileField
from wtforms.validators import DataRequired


class EmpForm(Form):
     nome       = StringField('Nome', validators=[DataRequired()])
     email      = StringField('email', validators=[DataRequired()])
     nome_resp  = StringField('Nome Responsável', validators=[DataRequired()])
     telegram   = StringField('Telegram', validators=[DataRequired()])

app/controllers/empresa/controllers.py
from flask import render_template, flash, redirect, request,session, redirect, Blueprint, url_for
from werkzeug import secure_filename
from app import db
from app.controllers.empresa.forms import EmpForm
from app.model import Empresa
from flask_login import login_required
import os



empresa = Blueprint('empresa',__name__)

@empresa.route('/index')
@empresa.route('/')
@login_required
def index():
    todos = Empresa.query.all()
    session['tela'] = "empresa"
    return render_template('empresa/index.html',title='Lista de Empresas',todos=todos)


@empresa.route('/new', methods=['GET','POST'])
@login_required
def new():
    form = EmpForm()
    if form.validate_on_submit():
       emp = Empresa(
                           nome   = form.nome.data,
                           email  = form.email.data,
                           nome_resp = form.nome_resp.data,
                           telegram  = form.telegram.data
                          )

       emp.add(emp)
       return redirect(url_for('empresa.index'))
    return render_template('empresa/new.html',title='Cadastro de Empresa',form=form)

@empresa.route("/edit/<int:emp_id>", methods = ["GET","POST"])
@login_required
def edit(emp_id):
    emp = Empresa.query.get(emp_id)
    src_path = emp.nome
    form = EmpForm(obj=emp)
    if form.validate_on_submit():
       emp.nome       = form.nome.data
       emp.email      = form.email.data
       emp.nome_resp  = form.nome_resp.data
       emp.telegram   = form.telegram.data
       emp.update(src_path,emp.nome)
       return redirect(url_for('empresa.index'))
    return render_template("empresa/edit.html",title='Alterar de Empresa', form=form)

@empresa.route("/delete/<int:emp_id>")
@login_required
def delete(emp_id):
    emp = Empresa.query.get(emp_id)
    if len(emp.Usuario.all()) == 0:
       emp.delete(emp)
    return redirect(url_for('empresa.index'))

app/templates/empresa/edit.html
<!-- extend from base layout -->

{% extends "layout/base.html" %}

{% block content %}
  <div class="form-horizontal">
    <form action="" method="post" name="new">
          {{form.hidden_tag() }}
      <p>
           {% for error in form.errors %}
                   <span style="color: red;">[{{ error }}] </span>
                {%  endfor%} <br>
       </p>

                 <div class="control-group">
             <label class="control-label" for="form-field-1">Nome</label>
            <div class="controls">
                     {{ form.nome(size=50) }}
            </div>
          </div>

               <div class="control-group">
             <label class="control-label" for="form-field-1">Nome do Responsável</label>
            <div class="controls">
                     {{form.nome_resp }}
            </div>
          </div>


               <div class="control-group">
             <label class="control-label" for="form-field-1">E-Mail</label>
            <div class="controls">
                     {{ form.email }}
            </div>
          </div>

               <div class="control-group">
             <label class="control-label" for="form-field-1">Telegram (nickname)</label>
            <div class="controls">
                     {{ form.telegram }}
            </div>
              </div>

               <div class="form-actions">
            <input type="submit" value="Salvar" class="btn btn-info">   
              </div>

      </form>
</div>
{% endblock %}

app/templates/empresa/index.html
{% extends "layout/base.html" %}

{% block content %}




          <div class="row-fluid">
            <div class="span12">
              <!--PAGE CONTENT BEGINS-->

              <div class="row-fluid">
                <div class="span12">
                  <table id="sample-table-1" class="table table-striped table-bordered table-hover">
                     <thead>                                                 
                        <tr>                      
                          <th> Nome </th>
                          <th> E-Mail </th>
                          <th> </th>
                       </tr>
                      </thead> 
                      <tbody>
                        {% for emp in todos %}
                          <tr>
                             <td> {{emp.nome}} </td>
                             <td> {{emp.email}}</td>
                             <td>
                                <div class="hidden-phone visible-desktop btn-group">                            
                                     <a class="btn btn-mini btn-info" href="{{url_for('empresa.edit', emp_id=emp.id)}}"> 
                                         <i class="icon-edit bigger-120">   </i>                                       
                                     </a>
                                     <a class="btn btn-mini btn-danger" href="{{url_for('empresa.delete', emp_id=emp.id)}}">
                                        <i class="icon-trash bigger-120"></i>
                                     </a>                           
                                </div>                         
                             </td>
                          </tr>
                        {% endfor %}
                      </tbody>  
             </table>
     
                </div><!--/span-->
              </div><!--/row-->

              
              <div class="hr hr-18 dotted hr-double"></div>
                           <div class="left">
                      <a href="{{url_for('empresa.new')}}" class="btn btn-primary">
                        <i class="icon-plus"></i>
                        <strong>Nova Empresa</strong>
                      </a>
                    </div>
              

              
            </div><!--/.span-->
          </div><!--/.row-fluid-->
        </div><!--/.page-content-->

        <div class="ace-settings-container" id="ace-settings-container">
          <div class="btn btn-app btn-mini btn-warning ace-settings-btn" id="ace-settings-btn">
            <i class="icon-cog bigger-150"></i>
          </div>

          <div class="ace-settings-box" id="ace-settings-box">
            <div>
              <div class="pull-left">
                <select id="skin-colorpicker" class="hide">
                  <option data-class="default" value="#438EB9" />#438EB9
                  <option data-class="skin-1" value="#222A2D" />#222A2D
                  <option data-class="skin-2" value="#C6487E" />#C6487E
                  <option data-class="skin-3" value="#D0D0D0" />#D0D0D0
                </select>
              </div>
              <span>&nbsp; Choose Skin</span>
            </div>

            <div>
              <input type="checkbox" class="ace-checkbox-2" id="ace-settings-header" />
              <label class="lbl" for="ace-settings-header"> Fixed Header</label>
            </div>

            <div>
              <input type="checkbox" class="ace-checkbox-2" id="ace-settings-sidebar" />
              <label class="lbl" for="ace-settings-sidebar"> Fixed Sidebar</label>
            </div>

            <div>
              <input type="checkbox" class="ace-checkbox-2" id="ace-settings-breadcrumbs" />
              <label class="lbl" for="ace-settings-breadcrumbs"> Fixed Breadcrumbs</label>
            </div>

            <div>
              <input type="checkbox" class="ace-checkbox-2" id="ace-settings-rtl" />
              <label class="lbl" for="ace-settings-rtl"> Right To Left (rtl)</label>
            </div>
          </div>
        </div><!--/#ace-settings-container-->
      </div><!--/.main-content-->
    </div><!--/.main-container-->

    <a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-small btn-inverse">
      <i class="icon-double-angle-up icon-only bigger-110"></i>
    </a>


{% endblock %}

app/templates/empresa/new.html
<!-- extend from base layout -->

{% extends "layout/base.html" %}

{% block content %}
  <div class="form-horizontal">
    <form action="" method="post" name="new">
          {{form.hidden_tag() }}
      <p>
           {% for error in form.errors %}
                   <span style="color: red;">[{{ error }}] </span>
                {%  endfor%} <br>
       </p>

                 <div class="control-group">
             <label class="control-label" for="form-field-1">Nome</label>
            <div class="controls">
                     {{ form.nome(size=50) }}
            </div>
          </div>

               <div class="control-group">
             <label class="control-label" for="form-field-1">Nome do Responsável</label>
            <div class="controls">
                     {{form.nome_resp }}
            </div>
          </div>


               <div class="control-group">
             <label class="control-label" for="form-field-1">E-Mail</label>
            <div class="controls">
                     {{ form.email }}
            </div>
          </div>

               <div class="control-group">
             <label class="control-label" for="form-field-1">Telegram (nickname)</label>
            <div class="controls">
                     {{ form.telegram }}
            </div>
              </div>

               <div class="form-actions">
            <input type="submit" value="Salvar" class="btn btn-info">   
              </div>

      </form>
</div>
{% endblock %}