app/controllers/usuario/forms.py
from flask_wtf import Form
from wtforms import StringField, BooleanField, FloatField, IntegerField, DateField,TextAreaField, SelectField, FileField, PasswordField,validators
from wtforms.validators import DataRequired, EqualTo
from app.model import Empresa

class UserForm(Form):
     nome       = StringField('Nome', validators=[DataRequired()])
     sobrenome  = StringField('SobreNome', validators=[DataRequired()])
     email      = StringField('E-Mail', validators=[DataRequired()])
     login      = StringField('Login', validators=[DataRequired()])
     password   = StringField('Password', validators=[DataRequired()])
     password   = PasswordField('New Password', [validators.Required(), validators.EqualTo('confirm', message='Passwords must match')])
     confirm    = PasswordField('Repeat Password')
     empresa_id = SelectField('Empresa', coerce=int)

app/controllers/usuario/controllers.py
from flask import render_template, flash, redirect, request,session, redirect, Blueprint, url_for
from werkzeug import secure_filename
from app import db
from app.controllers.usuario.forms import UserForm
from app.model import Usuario,Empresa
from flask_login import login_required




usuario = Blueprint('usuario',__name__)

@usuario.route('/index')
@usuario.route('/')
@login_required
def index():
    session['tela'] = "usuario"
    todos = Usuario.query.all() 
    return render_template('usuario/index.html',title='Lista de Usuario',todos=todos)


@usuario.route('/new', methods=['GET','POST'])
@login_required
def new():
    form = UserForm()    
    form.empresa_id.choices = [(h.id,h.nome) for h in Empresa.query.all()]
    if form.validate_on_submit():
       user = Usuario(
                           nome       = form.nome.data,
                           sobrenome  = form.sobrenome.data,
                           email      = form.email.data,
                           login      = form.login.data,
                           password   = form.password.data,
                           empresa_id = form.empresa_id.data
                          )
       print(user.add(user))
       return redirect(url_for('usuario.index'))
    return render_template('usuario/new.html',title='Cadastro de Usuario',form=form)



@usuario.route("/edit/<int:user_id>", methods = ["GET","POST"])
@login_required
def edit(user_id):
    user = Usuario.query.get(user_id)
    src_path = user.empresa.nome + '/' + user.nome
    form = UserForm(obj=user)
    form.empresa_id.choices = [(h.id,h.nome) for h in Empresa.query.all()]
    if form.validate_on_submit():
       user.nome       = form.nome.data
       user.sobrenome  = form.sobrenome.data
       user.email      = form.email.data
       user.login      = form.login.data
       user.password   = form.password.data
       user.empresa_id = form.empresa_id.data

       
       user.update()
       return redirect(url_for('usuario.index'))
    return render_template("usuario/edit.html",title='Alterar de Empresa', form=form)

@usuario.route("/delete/<int:user_id>")
@login_required
def delete(user_id):
    user = Usuario.query.get(user_id)
 
    # Verificar se existe movimentação do usuário antes de apagar ou apagar todas as movimentacoes
    user.delete(user)
    return redirect(url_for('usuario.index'))

app/templates/usuario/edit.html
<!-- extend from base layout -->

{% extends "layout/base.html" %}

{% block content %}
  <div class="form-horizontal">
    <form action="" method="post" name="edit">
          {{form.hidden_tag() }}
      <p>
           {% for error in form.errors %}
                   <span style="color: red;">[{{ error }}] </span>
                {%  endfor%} <br>
       </p>
               <div class="control-group">
             <label class="control-label" for="form-field-1">Nome</label>
            <div class="controls">
                     {{form.nome }}
            </div>
          </div>


               <div class="control-group">
             <label class="control-label" for="form-field-1">Sobrenome</label>
            <div class="controls">
                     {{ form.sobrenome }}
            </div>
          </div>

               <div class="control-group">
             <label class="control-label" for="form-field-1">E-mail</label>
            <div class="controls">
                     {{ form.email }}
            </div>
              </div>

               <div class="control-group">
             <label class="control-label" for="form-field-1">Login</label>
            <div class="controls">
                     {{ form.login }}
            </div>
              </div>


               <div class="control-group">
             <label class="control-label" for="form-field-1">Password</label>
            <div class="controls">
                     {{ form.password }}
            </div>
          </div>

               <div class="control-group">
             <label class="control-label" for="form-field-1">Confirmação Password</label>
            <div class="controls">
                     {{ form.confirm }}
            </div>
          </div>

               <div class="control-group">
             <label class="control-label" for="form-field-1">Empresa</label>
            <div class="controls">
                     {{form.empresa_id }}
            </div>
          </div>

               
               

               <div class="form-actions">
            <input type="submit" value="Salvar" class="btn btn-info">   
              </div>

      </form>
</div>
{% endblock %}







           

app/templates/usuario/index.html
{% extends "layout/base.html" %}

{% block content %}




          <div class="row-fluid">
            <div class="span12">
              <!--PAGE CONTENT BEGINS-->

              <div class="row-fluid">
                <div class="span12">
                  <table id="sample-table-1" class="table table-striped table-bordered table-hover">
                     <thead>                                                 
                        <tr>                      
                          <th> Nome </th>
                          <th> Sobrenome </th>
                          <th> E-Mail </th>
                          <th> Empresa </th>
                          <th></th>
                       </tr>
                      </thead> 
                      <tbody>
                        {% for user in todos %}
                          <tr>
                             <td> {{user.nome}} </td>
                             <td> {{user.sobrenome}}</td>
                             <td> {{user.email}}</td>
                             <td> {{user.empresa.nome}}</td>                             
                             <td>
                                <div class="hidden-phone visible-desktop btn-group">                            
                                     <a class="btn btn-mini btn-info" href="{{url_for('usuario.edit', user_id=user.id)}}"> 
                                         <i class="icon-edit bigger-120">   </i>                                       
                                     </a>
                                     <a class="btn btn-mini btn-danger" href="{{url_for('usuario.delete', user_id=user.id)}}">
                                        <i class="icon-trash bigger-120"></i>
                                     </a>                           
                                </div>                         
                             </td>
                          </tr>
                        {% endfor %}
                      </tbody>  
             </table>
     
                </div><!--/span-->
              </div><!--/row-->

              
              <div class="hr hr-18 dotted hr-double"></div>
                           <div class="left">
                      <a href="{{url_for('usuario.new')}}" class="btn btn-primary">
                        <i class="icon-plus"></i>
                        <strong>Novo Usuário</strong>
                      </a>
                    </div>
              

              
            </div><!--/.span-->
          </div><!--/.row-fluid-->
        </div><!--/.page-content-->

        <div class="ace-settings-container" id="ace-settings-container">
          <div class="btn btn-app btn-mini btn-warning ace-settings-btn" id="ace-settings-btn">
            <i class="icon-cog bigger-150"></i>
          </div>

          <div class="ace-settings-box" id="ace-settings-box">
            <div>
              <div class="pull-left">
                <select id="skin-colorpicker" class="hide">
                  <option data-class="default" value="#438EB9" />#438EB9
                  <option data-class="skin-1" value="#222A2D" />#222A2D
                  <option data-class="skin-2" value="#C6487E" />#C6487E
                  <option data-class="skin-3" value="#D0D0D0" />#D0D0D0
                </select>
              </div>
              <span>&nbsp; Choose Skin</span>
            </div>

            <div>
              <input type="checkbox" class="ace-checkbox-2" id="ace-settings-header" />
              <label class="lbl" for="ace-settings-header"> Fixed Header</label>
            </div>

            <div>
              <input type="checkbox" class="ace-checkbox-2" id="ace-settings-sidebar" />
              <label class="lbl" for="ace-settings-sidebar"> Fixed Sidebar</label>
            </div>

            <div>
              <input type="checkbox" class="ace-checkbox-2" id="ace-settings-breadcrumbs" />
              <label class="lbl" for="ace-settings-breadcrumbs"> Fixed Breadcrumbs</label>
            </div>

            <div>
              <input type="checkbox" class="ace-checkbox-2" id="ace-settings-rtl" />
              <label class="lbl" for="ace-settings-rtl"> Right To Left (rtl)</label>
            </div>
          </div>
        </div><!--/#ace-settings-container-->
      </div><!--/.main-content-->
    </div><!--/.main-container-->

    <a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-small btn-inverse">
      <i class="icon-double-angle-up icon-only bigger-110"></i>
    </a>


{% endblock %}

app/templates/usuario/new.html
<!-- extend from base layout -->

{% extends "layout/base.html" %}

{% block content %}
	<div class="form-horizontal">
    <form action="" method="post" name="new">
          {{form.hidden_tag() }}
      <p>
           {% for error in form.errors %}
                   <span style="color: red;">[{{ error }}] </span>
                {%  endfor%} <br>
       </p>
               <div class="control-group">
					   <label class="control-label" for="form-field-1">Nome</label>
					  <div class="controls">
                     {{form.nome }}
					  </div>
					</div>


               <div class="control-group">
					   <label class="control-label" for="form-field-1">Sobrenome</label>
					  <div class="controls">
                     {{ form.sobrenome }}
					  </div>
					</div>

               <div class="control-group">
					   <label class="control-label" for="form-field-1">E-mail</label>
					  <div class="controls">
                     {{ form.email }}
					  </div>
              </div>

               <div class="control-group">
					   <label class="control-label" for="form-field-1">Login</label>
					  <div class="controls">
                     {{ form.login }}
					  </div>
              </div>


               <div class="control-group">
					   <label class="control-label" for="form-field-1">Password</label>
					  <div class="controls">
                     {{ form.password }}
					  </div>
					</div>

               <div class="control-group">
					   <label class="control-label" for="form-field-1">Confirmação Password</label>
					  <div class="controls">
                     {{ form.confirm }}
					  </div>
					</div>

               <div class="control-group">
					   <label class="control-label" for="form-field-1">Empresa</label>
					  <div class="controls">
                     {{form.empresa_id }}
					  </div>
					</div>

               
               

               <div class="form-actions">
	  				<input type="submit" value="Salvar" class="btn btn-info">   
              </div>

      </form>
</div>
{% endblock %}







           