app/controllers/categoria/forms.py
from flask_wtf import Form
from wtforms import StringField, BooleanField, FloatField, IntegerField, DateField,TextAreaField, SelectField
from wtforms.validators import DataRequired

class CatForm(Form):

     titulo    = StringField('titulo', validators=[DataRequired()])
     descricao = StringField('titulo', validators=[DataRequired()])
     status    = SelectField('Tipo de Conta', choices=[('0','Entrada'),('1','Saída')])

app/controllers/categoria/__init__.py
from . import controllers

app/controllers/categoria/controllers.py
from app import db
from app.controllers.categoria.forms import CatForm
from flask_login import login_required, current_user
from flask_babel import format_currency, format_decimal
from app.model import Categoria, Empresa, Usuario, Planejamento, Movimentacao, Alert
from flask import render_template, flash, redirect, request,session, redirect, Blueprint, url_for

categoria = Blueprint('categoria',__name__)

@categoria.route('/index')
@categoria.route('/')
@login_required
def index():
    session['tela'] = 'categoria'
    todos = Categoria.query.filter(Categoria.empresa_id == session['empresa'] ).all()
    set_alerts(session['empresa'])
    return render_template('categoria/index.html', title = 'Lista de Categorias', todos = todos)

@categoria.route('/new', methods = ['GET','POST'])
@login_required
def new():
    form = CatForm()
    if form.validate_on_submit():
        cat = Categoria(
            titulo     = form.titulo.data,
            descricao  = form.descricao.data,
            keywords   = form.titulo.data,
            status     = form.status.data
        )
        cat.empresa_id = session['empresa']
        cat.add(cat)
        return redirect(url_for('categoria.index'))
    return render_template('categoria/new.html', title = 'Cadastro de Novas Contas', form = form)

@categoria.route('/edit/<int:cat_id>', methods = ['GET','POST'])
@login_required
def edit(cat_id):
    cat = Categoria.query.get(cat_id)
    form = CatForm(obj = cat)
    if form.validate_on_submit():
        cat.titulo     = form.titulo.data
        cat.descricao  = form.descricao.data
        cat.status     = form.status.data
        cat.update()
        return redirect(url_for('categoria.index'))
    return render_template('categoria/edit.html', title = 'Alterar de Empresa', form = form)

@categoria.route('/delete/<int:cat_id>')
@login_required
def delete(cat_id):
    cat = Categoria.query.get(cat_id)
    # Verifica se existe movimentação do usuário antes de apagar uma categoria
    movs = Movimentacao.query.filter(Movimentacao.categoria_id == cat_id).all()
    if len(movs) == 0:
        cat.delete(cat)
    return redirect(url_for('categoria.index'))

@categoria.context_processor
def dados():
    usuario = Usuario.query.get(current_user.id)
    empresa = Empresa.query.get(session['empresa'])
    set_alerts(session['empresa'])
    return dict(empresa = empresa.nome, usuario = usuario.nome)

def formatar_dinheiro(value):
    if type(value) == str:
        value = int(value)
    
    valor = format_decimal(value, format='#.##,##;(#)')
    return 'R$ {}'.format(valor)

def set_alerts(empresa_id):
    session['alerts'] = []
    plans = Planejamento.query.filter(Planejamento.empresa_id == empresa_id).all()
    if len(plans) > 0:
        for plan in plans:
            movs = Movimentacao.query.filter(Movimentacao.categoria_id == plan.categoria_id).all()
            
            sum_valor_movs = 0
            for mov in movs:
                sum_valor_movs = sum_valor_movs + abs(mov.valor)
            
            if sum_valor_movs >= plan.valor:
                session['alerts'].append(plan.titulo + ' - Valor Limite: ' + formatar_dinheiro((plan.valor)) + ' - Valor Atual: ' + formatar_dinheiro((sum_valor_movs)))

app/templates/categoria/edit.html
<!-- extend from base layout -->

{% extends "layout/base.html" %}

{% block content %}
   <h1> Alteração de Categoria </h1>
    <form action="" method="post" name="new">
          {{form.hidden_tag() }}
      <p>
           {% for error in form.errors %}
                   <span style="color: red;">[{{ error }}] </span>
                {%  endfor%} <br>
       </p>
          <p> 
              <p>
                 <label>Titulo: </label> <br/>            
                 {{ form.titulo(size=30) }} <br/>
              </p>
              <p>
                 <label>Descrição:</label> <br/>
                 {{ form.descricao(size=30) }} <br/>
              </p>
               <p>
                 <label>Tipo de Conta: </label>  <br/>
                    {{ form.status }} <br/>
               </p>   
          <p><input type="submit" value="Salvar"></p>
      </form>
{% endblock %}

app/templates/categoria/index.html
{% extends "layout/base.html" %}

{% block content %}




          <div class="row-fluid">
            <div class="span12">
              <!--PAGE CONTENT BEGINS-->

              <div class="row-fluid">
                <div class="span12">
                  <table id="sample-table-1" class="table table-striped table-bordered table-hover">
                     <thead>                                                 
                        <tr> 
                          <th> Código </th>                     
                          <th> Titulo </th>
                          <th> Descrição </th>
                          <th> Status </th>
                          <th> </th>
                       </tr>
                      </thead> 
                      <tbody>
                        {% for categoria in todos %}
                          <tr>
                             <td> {{categoria.id}}</td>
                             <td> {{categoria.titulo}} </td>
                             <td> {{categoria.descricao}}</td>
                             {% if categoria.status == 0 %}
                             <td> Entrada </td>
                             {% else %}
                             <td> Saida </td>
                             {% endif %}
                             <td>
                                <div class="hidden-phone visible-desktop btn-group">                            
                                     <a class="btn btn-mini btn-info" href="{{url_for('categoria.edit', cat_id=categoria.id)}}"> 
                                         <i class="icon-edit bigger-120">   </i>                                       
                                     </a>
                                     <a class="btn btn-mini btn-danger" href="{{url_for('categoria.delete', cat_id=categoria.id)}}">
                                        <i class="icon-trash bigger-120"></i>
                                     </a>                           
                                </div>                         
                             </td>
                          </tr>
                        {% endfor %}
                      </tbody>  
             </table>
     
                </div><!--/span-->
              </div><!--/row-->

              
              <div class="hr hr-18 dotted hr-double"></div>
                           <div class="left">
                      <a href="{{url_for('categoria.new')}}" class="btn btn-primary">
                        <i class="icon-plus"></i>
                        <strong>Nova Categoria</strong>
                      </a>
                    </div>
              

              
            </div><!--/.span-->
          </div><!--/.row-fluid-->
        </div><!--/.page-content-->

        <div class="ace-settings-container" id="ace-settings-container">
          <div class="btn btn-app btn-mini btn-warning ace-settings-btn" id="ace-settings-btn">
            <i class="icon-cog bigger-150"></i>
          </div>

          <div class="ace-settings-box" id="ace-settings-box">
            <div>
              <div class="pull-left">
                <select id="skin-colorpicker" class="hide">
                  <option data-class="default" value="#438EB9" />#438EB9
                  <option data-class="skin-1" value="#222A2D" />#222A2D
                  <option data-class="skin-2" value="#C6487E" />#C6487E
                  <option data-class="skin-3" value="#D0D0D0" />#D0D0D0
                </select>
              </div>
              <span>&nbsp; Choose Skin</span>
            </div>

            <div>
              <input type="checkbox" class="ace-checkbox-2" id="ace-settings-header" />
              <label class="lbl" for="ace-settings-header"> Fixed Header</label>
            </div>

            <div>
              <input type="checkbox" class="ace-checkbox-2" id="ace-settings-sidebar" />
              <label class="lbl" for="ace-settings-sidebar"> Fixed Sidebar</label>
            </div>

            <div>
              <input type="checkbox" class="ace-checkbox-2" id="ace-settings-breadcrumbs" />
              <label class="lbl" for="ace-settings-breadcrumbs"> Fixed Breadcrumbs</label>
            </div>

            <div>
              <input type="checkbox" class="ace-checkbox-2" id="ace-settings-rtl" />
              <label class="lbl" for="ace-settings-rtl"> Right To Left (rtl)</label>
            </div>
          </div>
        </div><!--/#ace-settings-container-->
      </div><!--/.main-content-->
    </div><!--/.main-container-->

    <a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-small btn-inverse">
      <i class="icon-double-angle-up icon-only bigger-110"></i>
    </a>


{% endblock %}

app/templates/categoria/new.html
<!-- extend from base layout -->

{% extends "layout/base.html" %}

{% block content %}
   <h1> Cadastro de Novas Categorias</h1>
    <form action="" method="post" name="new">
          {{form.hidden_tag() }}
      <p>
           {% for error in form.errors %}
                   <span style="color: red;">[{{ error }}] </span>
                {%  endfor%} <br>
       </p>
          <p> 
              <p>
                 <label>Titulo: </label> <br/>            
                 {{ form.titulo(size=30) }} <br/>
              </p>
              <p>
                 <label>Descrição:</label> <br/>
                 {{ form.descricao(size=30) }} <br/>
              </p>
               <p>
                 <label>Tipo de Conta: </label>  <br/>
                    {{ form.status }} <br/>
               </p>   
          <p><input type="submit" value="Salvar"></p>
      </form>
{% endblock %}